version: "3.7"
services:
  web:
    image: nginx:alpine
    ports:
      - 8080:80
    networks:
      - frontend
    restart: always
  app:
    build: ./app
    ports:
      - 8501:8501
    networks:
      - frontend
    restart: always
networks:
  frontend:
    driver: bridge
